[{'Certificado': '',
  'Conceptos': [{'Cantidad': Decimal('1'),
                 'ClaveProdServ': Code('10101702', 'Trucha viva'),
                 'ClaveUnidad': Code('E48', 'Unidad de servicio'),
                 'Descripcion': 'SOME MES DE ABRIL DEL 2023',
                 'Importe': Decimal('18950.00'),
                 'Impuestos': {'Retenciones': {'001|Tasa|0.100000': {'Base': Decimal('18950.00'),
                                                                     'Importe': Decimal('1895.00'),
                                                                     'Impuesto': Code('001', 'ISR'),
                                                                     'TasaOCuota': Decimal('0.100000'),
                                                                     'TipoFactor': Code('Tasa', None)},
                                               '002|Tasa|0.106667': {'Base': Decimal('18950.00'),
                                                                     'Importe': Decimal('2021.34'),
                                                                     'Impuesto': Code('002', 'IVA'),
                                                                     'TasaOCuota': Decimal('0.106667'),
                                                                     'TipoFactor': Code('Tasa', None)}},
                               'Traslados': {'002|Tasa|0.160000': {'Base': Decimal('18950.00'),
                                                                   'Importe': Decimal('3032.00'),
                                                                   'Impuesto': Code('002', 'IVA'),
                                                                   'TasaOCuota': Decimal('0.160000'),
                                                                   'TipoFactor': Code('Tasa', None)}}},
                 'ObjetoImp': Code('02', 'Sí objeto de impuesto'),
                 'ValorUnitario': Decimal('18950.00')}],
  'Emisor': {'Nombre': 'CACERES XAVIER',
             'RegimenFiscal': Code('612', 'Personas Físicas con Actividades Empresariales y Profesionales'),
             'Rfc': 'CACX7605101P8'},
  'Exportacion': Code('01', 'No aplica'),
  'Fecha': datetime.datetime(2022, 1, 1, 0, 0),
  'FormaPago': Code('03', 'Transferencia electrónica de fondos'),
  'Impuestos': {'Retenciones': {'001': {'Importe': Decimal('1895.00'),
                                        'Impuesto': Code('001', 'ISR')},
                                '002': {'Importe': Decimal('2021.34'),
                                        'Impuesto': Code('002', 'IVA')}},
                'TotalImpuestosRetenidos': Decimal('3916.34'),
                'TotalImpuestosTrasladados': Decimal('3032.00'),
                'Traslados': {'002|Tasa|0.160000': {'Base': Decimal('18950.00'),
                                                    'Importe': Decimal('3032.00'),
                                                    'Impuesto': Code('002', 'IVA'),
                                                    'TasaOCuota': Decimal('0.160000'),
                                                    'TipoFactor': Code('Tasa', None)}}},
  'LugarExpedicion': '64264',
  'MetodoPago': Code('PUE', 'Pago en una sola exhibición'),
  'Moneda': Code('MXN', 'Peso Mexicano'),
  'NoCertificado': '',
  'Receptor': {'DomicilioFiscalReceptor': '64264',
               'Nombre': 'SERVICIOS COMERCIALES ANDREA',
               'RegimenFiscalReceptor': Code('601', 'General de Ley Personas Morales'),
               'Rfc': 'ABV9901115S7',
               'UsoCFDI': Code('G03', 'Gastos en general')},
  'Sello': '',
  'SubTotal': Decimal('18950.00'),
  'TipoDeComprobante': Code('I', 'Ingreso'),
  'Total': Decimal('18065.66'),
  'Version': '4.0'},
 {'Certificado': '',
  'Conceptos': [{'Cantidad': Decimal('1'),
                 'ClaveProdServ': Code('10101702', 'Trucha viva'),
                 'ClaveUnidad': Code('E48', 'Unidad de servicio'),
                 'Descripcion': 'SOME MES DE MAYO DEL 2023',
                 'Importe': Decimal('34500.00'),
                 'Impuestos': {'Retenciones': {'001|Tasa|0.100000': {'Base': Decimal('34500.00'),
                                                                     'Importe': Decimal('3450.00'),
                                                                     'Impuesto': Code('001', 'ISR'),
                                                                     'TasaOCuota': Decimal('0.100000'),
                                                                     'TipoFactor': Code('Tasa', None)}},
                               'Traslados': {'002|Tasa|0.160000': {'Base': Decimal('34500.00'),
                                                                   'Importe': Decimal('5520.00'),
                                                                   'Impuesto': Code('002', 'IVA'),
                                                                   'TasaOCuota': Decimal('0.160000'),
                                                                   'TipoFactor': Code('Tasa', None)}}},
                 'ObjetoImp': Code('02', 'Sí objeto de impuesto'),
                 'ValorUnitario': Decimal('34500.00')}],
  'Emisor': {'Nombre': 'CACERES XAVIER',
             'RegimenFiscal': Code('612', 'Personas Físicas con Actividades Empresariales y Profesionales'),
             'Rfc': 'CACX7605101P8'},
  'Exportacion': Code('01', 'No aplica'),
  'Fecha': datetime.datetime(2022, 1, 1, 0, 0),
  'FormaPago': Code('99', 'Por definir'),
  'Impuestos': {'Retenciones': {'001': {'Importe': Decimal('3450.00'),
                                        'Impuesto': Code('001', 'ISR')}},
                'TotalImpuestosRetenidos': Decimal('3450.00'),
                'TotalImpuestosTrasladados': Decimal('5520.00'),
                'Traslados': {'002|Tasa|0.160000': {'Base': Decimal('34500.00'),
                                                    'Importe': Decimal('5520.00'),
                                                    'Impuesto': Code('002', 'IVA'),
                                                    'TasaOCuota': Decimal('0.160000'),
                                                    'TipoFactor': Code('Tasa', None)}}},
  'LugarExpedicion': '64264',
  'MetodoPago': Code('PPD', 'Pago en parcialidades o diferido'),
  'Moneda': Code('MXN', 'Peso Mexicano'),
  'NoCertificado': '',
  'Receptor': {'DomicilioFiscalReceptor': '64264',
               'Nombre': 'INSTITUTO EDUCATIVO DE EDUCACION BASICA',
               'RegimenFiscalReceptor': Code('603', 'Personas Morales con Fines no Lucrativos'),
               'Rfc': 'ABC1511034U3',
               'UsoCFDI': Code('G03', 'Gastos en general')},
  'Sello': '',
  'SubTotal': Decimal('34500.00'),
  'TipoDeComprobante': Code('I', 'Ingreso'),
  'Total': Decimal('36570.00'),
  'Version': '4.0'},
 {'Certificado': '',
  'Conceptos': [{'Cantidad': Decimal('1'),
                 'ClaveProdServ': Code('10101702', 'Trucha viva'),
                 'ClaveUnidad': Code('E48', 'Unidad de servicio'),
                 'Descripcion': 'SOME MES DE ABRIL DEL 2023',
                 'Importe': Decimal('31913.07'),
                 'Impuestos': {'Traslados': {'002|Tasa|0.160000': {'Base': Decimal('31913.07'),
                                                                   'Importe': Decimal('5106.09'),
                                                                   'Impuesto': Code('002', 'IVA'),
                                                                   'TasaOCuota': Decimal('0.160000'),
                                                                   'TipoFactor': Code('Tasa', None)}}},
                 'ObjetoImp': Code('02', 'Sí objeto de impuesto'),
                 'ValorUnitario': Decimal('31913.07')}],
  'Emisor': {'Nombre': 'CACERES XAVIER',
             'RegimenFiscal': Code('612', 'Personas Físicas con Actividades Empresariales y Profesionales'),
             'Rfc': 'CACX7605101P8'},
  'Exportacion': Code('01', 'No aplica'),
  'Fecha': datetime.datetime(2022, 1, 1, 0, 0),
  'FormaPago': Code('99', 'Por definir'),
  'Impuestos': {'TotalImpuestosTrasladados': Decimal('5106.09'),
                'Traslados': {'002|Tasa|0.160000': {'Base': Decimal('31913.07'),
                                                    'Importe': Decimal('5106.09'),
                                                    'Impuesto': Code('002', 'IVA'),
                                                    'TasaOCuota': Decimal('0.160000'),
                                                    'TipoFactor': Code('Tasa', None)}}},
  'LugarExpedicion': '64264',
  'MetodoPago': Code('PPD', 'Pago en parcialidades o diferido'),
  'Moneda': Code('MXN', 'Peso Mexicano'),
  'NoCertificado': '',
  'Receptor': {'DomicilioFiscalReceptor': '64264',
               'Nombre': 'PEPE ALEJANDRO LOPEZ',
               'RegimenFiscalReceptor': Code('621', 'Incorporación Fiscal'),
               'Rfc': 'ABMG891115PD7',
               'UsoCFDI': Code('G03', 'Gastos en general')},
  'Sello': '',
  'SubTotal': Decimal('31913.07'),
  'TipoDeComprobante': Code('I', 'Ingreso'),
  'Total': Decimal('37019.16'),
  'Version': '4.0'}]