[{'Certificado': 'MIIF0TCCA7mgAwIBAgIUMzAwMDEwMDAwMDA0MDAwMDIzMDAwDQYJKoZIhvcNAQELBQAwggErMQ8wDQYDVQQDDAZBQyBVQVQxLjAsBgNVBAoMJVNFUlZJQ0lPIERFIEFETUlOSVNUUkFDSU9OIFRSSUJVVEFSSUExGjAYBgNVBAsMEVNBVC1JRVMgQXV0aG9yaXR5MSgwJgYJKoZIhvcNAQkBFhlvc2Nhci5tYXJ0aW5lekBzYXQuZ29iLm14MR0wGwYDVQQJDBQzcmEgY2VycmFkYSBkZSBjYWRpejEOMAwGA1UEEQwFMDYzNzAxCzAJBgNVBAYTAk1YMRkwFwYDVQQIDBBDSVVEQUQgREUgTUVYSUNPMREwDwYDVQQHDAhDT1lPQUNBTjERMA8GA1UELRMIMi41LjQuNDUxJTAjBgkqhkiG9w0BCQITFnJlc3BvbnNhYmxlOiBBQ0RNQS1TQVQwHhcNMTkwNTI4MjE0OTU0WhcNMjMwNTI3MjE0OTU0WjCBxjEdMBsGA1UEAxMUWE9DSElMVCBDQVNBUyBDSEFWRVoxHTAbBgNVBCkTFFhPQ0hJTFQgQ0FTQVMgQ0hBVkVaMR0wGwYDVQQKExRYT0NISUxUIENBU0FTIENIQVZFWjELMAkGA1UEBhMCTVgxJTAjBgkqhkiG9w0BCQEWFnBydWViYXNAcHJ1ZWJhcy5nb2IubXgxFjAUBgNVBC0TDUNBQ1g3NjA1MTAxUDgxGzAZBgNVBAUTEkNBQ1g3NjA1MTBNR1RTSEMwNDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALZlUIdao+OePGQShtKbc+ChwYJwVH+w2K4bTMnsDW0vkCdD+zBg2IBUhJxwEs3lKC5ZPB0yZupT0Pj2700rbDs8nZK7NY47Cyy9XnzQzDoAoDIUcO1S0ywGHHmDiqEZNCAYFkZy3FRnFQAWRpzAp8CnfttESprkUZ758mcQ9lsQNZFP+vQ7EtfHUSPH2OsBlmnyHeWmuG76jJAPpZwZuObtRiCTNR3MjIB5ac8Dz6jzx5SdZWZyfnJU20iZ2KDq7pdrJKfOnkNN6ilhaqzIAuo3WQERM1pqhLoxNsYdTfI7b4wi3czzeNjETcQiwWzbJ12r3bQKLmKrjcQvG1cPYhsCAwEAAaNPME0wDAYDVR0TAQH/BAIwADALBgNVHQ8EBAMCA9gwEQYJYIZIAYb4QgEBBAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMEBggrBgEFBQcDAjANBgkqhkiG9w0BAQsFAAOCAgEAXtkopoVbWb555Nx9AAmT2hOjkILYW+kCcdldQG+dPmmrJveBuIuUwTcV7JUaSyJ9ZtdXnMURNT3VrXCyWcMFc6nYzF2ZCmMasKzVakn5Zdd7vswKFMKLpeEam/Z16b8++l/ZB/QQgd6HG0jm02ro6MDRqKJFFCJgVq+Sofvui3NxAxqcXs6YxqXn0gexIGknb//LE1qQDHGU2zfz9Yas2o7doVLk2Bzgrb3MdYolmENUNzVNzWjaa7ear2yzY0HrDgqpVD895kkXjaI1ADrBix1t5WItj1XkMm9x7S5iVUtpGL5wyaQINSXf82GZntuLrOjJr9NCJnyS1+mVc6AxYI1r8AdkDHBU/vdmBhYoEf5ccysE6JNasl3jMl0LrgqZt9qfzMBAWAycFsT8Zqn+O5p/cS/9CaZEQz0HSJhuUCLGeq6Rc3ptJ+DJcc5KJB9rbxRaGh6k7U51LL5qnhFvIL7+OWuife2gHLMRr+AnIC1CXt9e9RFl5d7ERyr0pcBzJGp+3W+QBNneInRWfgH1JgzvUG7NkirPmUsKF0wXcCk1RzJU3F998QkYCb+kLXCYtedCe7G7wKkssEPt8+HYbnKPWQZwkPVgkKov/zyr843ZX1qj/kXyIBicREvBtI7IkWZpxKfapf8XsTHQMRFoBrzi9w6/85tJaz8BZGfpA1I=',
  'Conceptos': [{'Cantidad': Decimal('1'),
                 'ClaveProdServ': Code('10101702', 'Trucha viva'),
                 'ClaveUnidad': Code('E48', 'Unidad de servicio'),
                 'Descripcion': 'SOME MES DE ABRIL DEL 2023',
                 'Importe': Decimal('18950.00'),
                 'Impuestos': {'Retenciones': {'001|Tasa|0.100000': {'Base': Decimal('18950.00'),
                                                                     'Importe': Decimal('1895.00'),
                                                                     'Impuesto': Code('001', 'ISR'),
                                                                     'TasaOCuota': Decimal('0.100000'),
                                                                     'TipoFactor': Code('Tasa', None)},
                                               '002|Tasa|0.106667': {'Base': Decimal('18950.00'),
                                                                     'Importe': Decimal('2021.34'),
                                                                     'Impuesto': Code('002', 'IVA'),
                                                                     'TasaOCuota': Decimal('0.106667'),
                                                                     'TipoFactor': Code('Tasa', None)}},
                               'Traslados': {'002|Tasa|0.160000': {'Base': Decimal('18950.00'),
                                                                   'Importe': Decimal('3032.00'),
                                                                   'Impuesto': Code('002', 'IVA'),
                                                                   'TasaOCuota': Decimal('0.160000'),
                                                                   'TipoFactor': Code('Tasa', None)}}},
                 'ObjetoImp': Code('02', 'Sí objeto de impuesto'),
                 'ValorUnitario': Decimal('18950.00')}],
  'Emisor': {'Nombre': 'CACERES XAVIER',
             'RegimenFiscal': Code('612', 'Personas Físicas con Actividades Empresariales y Profesionales'),
             'Rfc': 'CACX7605101P8'},
  'Exportacion': Code('01', 'No aplica'),
  'Fecha': datetime.datetime(2022, 1, 1, 0, 0),
  'Folio': '1000',
  'FormaPago': Code('03', 'Transferencia electrónica de fondos'),
  'Impuestos': {'Retenciones': {'001': {'Importe': Decimal('1895.00'),
                                        'Impuesto': Code('001', 'ISR')},
                                '002': {'Importe': Decimal('2021.34'),
                                        'Impuesto': Code('002', 'IVA')}},
                'TotalImpuestosRetenidos': Decimal('3916.34'),
                'TotalImpuestosTrasladados': Decimal('3032.00'),
                'Traslados': {'002|Tasa|0.160000': {'Base': Decimal('18950.00'),
                                                    'Importe': Decimal('3032.00'),
                                                    'Impuesto': Code('002', 'IVA'),
                                                    'TasaOCuota': Decimal('0.160000'),
                                                    'TipoFactor': Code('Tasa', None)}}},
  'LugarExpedicion': Code('64264', None),
  'MetodoPago': Code('PUE', 'Pago en una sola exhibición'),
  'Moneda': Code('MXN', 'Peso Mexicano'),
  'NoCertificado': '30001000000400002300',
  'Receptor': {'DomicilioFiscalReceptor': '64264',
               'Nombre': 'SERVICIOS COMERCIALES ANDREA',
               'RegimenFiscalReceptor': Code('601', 'General de Ley Personas Morales'),
               'Rfc': 'ABV9901115S7',
               'UsoCFDI': Code('G03', 'Gastos en general')},
  'Sello': 'ocKcEDHyzK5A+jhsQ1UTt3gtVjtppGMKGy2dMww/vacnR0IGb7twnllwU8HQkFT0X2ZtLCU2VLOswLpkjlgAAtqtfKSzRVXZFJeVg48XpOrWM2mxtr0GPv11lOBk9G9LFI9s6nzzZ6dwOqWAahWEijkRvzrFRsBdc2lftgWK1ekF6/HdYsMZxUvKZYt0kYuYCYp5QmIyCpoj78qAkWBdxjFLB85mwwLDLL0bfn5IALfs2yP+FS/tQgxMEA2hNDvc6RMfbhHsCmaW8KGrYFa0dlctXq1xnmcVbCmYiQJTxfx6Te9uIe9QCFn/7UcNJpsQIK4LLwdAcN3TC/vKTfXhlg==',
  'Serie': 'K',
  'SubTotal': Decimal('18950.00'),
  'TipoDeComprobante': Code('I', 'Ingreso'),
  'Total': Decimal('18065.66'),
  'Version': '4.0'},
 {'Certificado': 'MIIF0TCCA7mgAwIBAgIUMzAwMDEwMDAwMDA0MDAwMDIzMDAwDQYJKoZIhvcNAQELBQAwggErMQ8wDQYDVQQDDAZBQyBVQVQxLjAsBgNVBAoMJVNFUlZJQ0lPIERFIEFETUlOSVNUUkFDSU9OIFRSSUJVVEFSSUExGjAYBgNVBAsMEVNBVC1JRVMgQXV0aG9yaXR5MSgwJgYJKoZIhvcNAQkBFhlvc2Nhci5tYXJ0aW5lekBzYXQuZ29iLm14MR0wGwYDVQQJDBQzcmEgY2VycmFkYSBkZSBjYWRpejEOMAwGA1UEEQwFMDYzNzAxCzAJBgNVBAYTAk1YMRkwFwYDVQQIDBBDSVVEQUQgREUgTUVYSUNPMREwDwYDVQQHDAhDT1lPQUNBTjERMA8GA1UELRMIMi41LjQuNDUxJTAjBgkqhkiG9w0BCQITFnJlc3BvbnNhYmxlOiBBQ0RNQS1TQVQwHhcNMTkwNTI4MjE0OTU0WhcNMjMwNTI3MjE0OTU0WjCBxjEdMBsGA1UEAxMUWE9DSElMVCBDQVNBUyBDSEFWRVoxHTAbBgNVBCkTFFhPQ0hJTFQgQ0FTQVMgQ0hBVkVaMR0wGwYDVQQKExRYT0NISUxUIENBU0FTIENIQVZFWjELMAkGA1UEBhMCTVgxJTAjBgkqhkiG9w0BCQEWFnBydWViYXNAcHJ1ZWJhcy5nb2IubXgxFjAUBgNVBC0TDUNBQ1g3NjA1MTAxUDgxGzAZBgNVBAUTEkNBQ1g3NjA1MTBNR1RTSEMwNDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALZlUIdao+OePGQShtKbc+ChwYJwVH+w2K4bTMnsDW0vkCdD+zBg2IBUhJxwEs3lKC5ZPB0yZupT0Pj2700rbDs8nZK7NY47Cyy9XnzQzDoAoDIUcO1S0ywGHHmDiqEZNCAYFkZy3FRnFQAWRpzAp8CnfttESprkUZ758mcQ9lsQNZFP+vQ7EtfHUSPH2OsBlmnyHeWmuG76jJAPpZwZuObtRiCTNR3MjIB5ac8Dz6jzx5SdZWZyfnJU20iZ2KDq7pdrJKfOnkNN6ilhaqzIAuo3WQERM1pqhLoxNsYdTfI7b4wi3czzeNjETcQiwWzbJ12r3bQKLmKrjcQvG1cPYhsCAwEAAaNPME0wDAYDVR0TAQH/BAIwADALBgNVHQ8EBAMCA9gwEQYJYIZIAYb4QgEBBAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMEBggrBgEFBQcDAjANBgkqhkiG9w0BAQsFAAOCAgEAXtkopoVbWb555Nx9AAmT2hOjkILYW+kCcdldQG+dPmmrJveBuIuUwTcV7JUaSyJ9ZtdXnMURNT3VrXCyWcMFc6nYzF2ZCmMasKzVakn5Zdd7vswKFMKLpeEam/Z16b8++l/ZB/QQgd6HG0jm02ro6MDRqKJFFCJgVq+Sofvui3NxAxqcXs6YxqXn0gexIGknb//LE1qQDHGU2zfz9Yas2o7doVLk2Bzgrb3MdYolmENUNzVNzWjaa7ear2yzY0HrDgqpVD895kkXjaI1ADrBix1t5WItj1XkMm9x7S5iVUtpGL5wyaQINSXf82GZntuLrOjJr9NCJnyS1+mVc6AxYI1r8AdkDHBU/vdmBhYoEf5ccysE6JNasl3jMl0LrgqZt9qfzMBAWAycFsT8Zqn+O5p/cS/9CaZEQz0HSJhuUCLGeq6Rc3ptJ+DJcc5KJB9rbxRaGh6k7U51LL5qnhFvIL7+OWuife2gHLMRr+AnIC1CXt9e9RFl5d7ERyr0pcBzJGp+3W+QBNneInRWfgH1JgzvUG7NkirPmUsKF0wXcCk1RzJU3F998QkYCb+kLXCYtedCe7G7wKkssEPt8+HYbnKPWQZwkPVgkKov/zyr843ZX1qj/kXyIBicREvBtI7IkWZpxKfapf8XsTHQMRFoBrzi9w6/85tJaz8BZGfpA1I=',
  'Conceptos': [{'Cantidad': Decimal('1'),
                 'ClaveProdServ': Code('10101702', 'Trucha viva'),
                 'ClaveUnidad': Code('E48', 'Unidad de servicio'),
                 'Descripcion': 'SOME MES DE MAYO DEL 2023',
                 'Importe': Decimal('34500.00'),
                 'Impuestos': {'Retenciones': {'001|Tasa|0.100000': {'Base': Decimal('34500.00'),
                                                                     'Importe': Decimal('3450.00'),
                                                                     'Impuesto': Code('001', 'ISR'),
                                                                     'TasaOCuota': Decimal('0.100000'),
                                                                     'TipoFactor': Code('Tasa', None)}},
                               'Traslados': {'002|Tasa|0.160000': {'Base': Decimal('34500.00'),
                                                                   'Importe': Decimal('5520.00'),
                                                                   'Impuesto': Code('002', 'IVA'),
                                                                   'TasaOCuota': Decimal('0.160000'),
                                                                   'TipoFactor': Code('Tasa', None)}}},
                 'ObjetoImp': Code('02', 'Sí objeto de impuesto'),
                 'ValorUnitario': Decimal('34500.00')}],
  'Emisor': {'Nombre': 'CACERES XAVIER',
             'RegimenFiscal': Code('612', 'Personas Físicas con Actividades Empresariales y Profesionales'),
             'Rfc': 'CACX7605101P8'},
  'Exportacion': Code('01', 'No aplica'),
  'Fecha': datetime.datetime(2022, 1, 1, 0, 0),
  'Folio': '1001',
  'FormaPago': Code('99', 'Por definir'),
  'Impuestos': {'Retenciones': {'001': {'Importe': Decimal('3450.00'),
                                        'Impuesto': Code('001', 'ISR')}},
                'TotalImpuestosRetenidos': Decimal('3450.00'),
                'TotalImpuestosTrasladados': Decimal('5520.00'),
                'Traslados': {'002|Tasa|0.160000': {'Base': Decimal('34500.00'),
                                                    'Importe': Decimal('5520.00'),
                                                    'Impuesto': Code('002', 'IVA'),
                                                    'TasaOCuota': Decimal('0.160000'),
                                                    'TipoFactor': Code('Tasa', None)}}},
  'LugarExpedicion': Code('64264', None),
  'MetodoPago': Code('PPD', 'Pago en parcialidades o diferido'),
  'Moneda': Code('MXN', 'Peso Mexicano'),
  'NoCertificado': '30001000000400002300',
  'Receptor': {'DomicilioFiscalReceptor': '64264',
               'Nombre': 'INSTITUTO EDUCATIVO DE EDUCACION BASICA',
               'RegimenFiscalReceptor': Code('603', 'Personas Morales con Fines no Lucrativos'),
               'Rfc': 'ABC1511034U3',
               'UsoCFDI': Code('G03', 'Gastos en general')},
  'Sello': 'k92LCZEVZZyQi8OhTAsbY98cvEjsonH6Hp3HnQr8TTE7ZqAhQDJdsQjSZVD8RNchbc2k+lg3gIM6cbUNc07U17hR4pSd3M7XHn7s43On0QQ/uoymV2+tw2a7IxzhItcMok8pcktBI5lyjX5ttYRzo0f2p2c33Y2e2H+U8uMmBSpGQx0eJKWTa1oePdPCCMjIie5zFDrTVePi1hEg8vUWHu53IiBbPJrQuqyWS4CrF0t5LrKSTVFcmfRJKHWBK/dIoYeWd6yXJN9GmWP/oFJmsw8GL+2YhUj+1xQoskpeLTasWImTyu5H539cDv7PPbUqJgWTJuNvsIKfPCoPGux1JQ==',
  'Serie': 'K',
  'SubTotal': Decimal('34500.00'),
  'TipoDeComprobante': Code('I', 'Ingreso'),
  'Total': Decimal('36570.00'),
  'Version': '4.0'},
 {'Certificado': 'MIIF0TCCA7mgAwIBAgIUMzAwMDEwMDAwMDA0MDAwMDIzMDAwDQYJKoZIhvcNAQELBQAwggErMQ8wDQYDVQQDDAZBQyBVQVQxLjAsBgNVBAoMJVNFUlZJQ0lPIERFIEFETUlOSVNUUkFDSU9OIFRSSUJVVEFSSUExGjAYBgNVBAsMEVNBVC1JRVMgQXV0aG9yaXR5MSgwJgYJKoZIhvcNAQkBFhlvc2Nhci5tYXJ0aW5lekBzYXQuZ29iLm14MR0wGwYDVQQJDBQzcmEgY2VycmFkYSBkZSBjYWRpejEOMAwGA1UEEQwFMDYzNzAxCzAJBgNVBAYTAk1YMRkwFwYDVQQIDBBDSVVEQUQgREUgTUVYSUNPMREwDwYDVQQHDAhDT1lPQUNBTjERMA8GA1UELRMIMi41LjQuNDUxJTAjBgkqhkiG9w0BCQITFnJlc3BvbnNhYmxlOiBBQ0RNQS1TQVQwHhcNMTkwNTI4MjE0OTU0WhcNMjMwNTI3MjE0OTU0WjCBxjEdMBsGA1UEAxMUWE9DSElMVCBDQVNBUyBDSEFWRVoxHTAbBgNVBCkTFFhPQ0hJTFQgQ0FTQVMgQ0hBVkVaMR0wGwYDVQQKExRYT0NISUxUIENBU0FTIENIQVZFWjELMAkGA1UEBhMCTVgxJTAjBgkqhkiG9w0BCQEWFnBydWViYXNAcHJ1ZWJhcy5nb2IubXgxFjAUBgNVBC0TDUNBQ1g3NjA1MTAxUDgxGzAZBgNVBAUTEkNBQ1g3NjA1MTBNR1RTSEMwNDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALZlUIdao+OePGQShtKbc+ChwYJwVH+w2K4bTMnsDW0vkCdD+zBg2IBUhJxwEs3lKC5ZPB0yZupT0Pj2700rbDs8nZK7NY47Cyy9XnzQzDoAoDIUcO1S0ywGHHmDiqEZNCAYFkZy3FRnFQAWRpzAp8CnfttESprkUZ758mcQ9lsQNZFP+vQ7EtfHUSPH2OsBlmnyHeWmuG76jJAPpZwZuObtRiCTNR3MjIB5ac8Dz6jzx5SdZWZyfnJU20iZ2KDq7pdrJKfOnkNN6ilhaqzIAuo3WQERM1pqhLoxNsYdTfI7b4wi3czzeNjETcQiwWzbJ12r3bQKLmKrjcQvG1cPYhsCAwEAAaNPME0wDAYDVR0TAQH/BAIwADALBgNVHQ8EBAMCA9gwEQYJYIZIAYb4QgEBBAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMEBggrBgEFBQcDAjANBgkqhkiG9w0BAQsFAAOCAgEAXtkopoVbWb555Nx9AAmT2hOjkILYW+kCcdldQG+dPmmrJveBuIuUwTcV7JUaSyJ9ZtdXnMURNT3VrXCyWcMFc6nYzF2ZCmMasKzVakn5Zdd7vswKFMKLpeEam/Z16b8++l/ZB/QQgd6HG0jm02ro6MDRqKJFFCJgVq+Sofvui3NxAxqcXs6YxqXn0gexIGknb//LE1qQDHGU2zfz9Yas2o7doVLk2Bzgrb3MdYolmENUNzVNzWjaa7ear2yzY0HrDgqpVD895kkXjaI1ADrBix1t5WItj1XkMm9x7S5iVUtpGL5wyaQINSXf82GZntuLrOjJr9NCJnyS1+mVc6AxYI1r8AdkDHBU/vdmBhYoEf5ccysE6JNasl3jMl0LrgqZt9qfzMBAWAycFsT8Zqn+O5p/cS/9CaZEQz0HSJhuUCLGeq6Rc3ptJ+DJcc5KJB9rbxRaGh6k7U51LL5qnhFvIL7+OWuife2gHLMRr+AnIC1CXt9e9RFl5d7ERyr0pcBzJGp+3W+QBNneInRWfgH1JgzvUG7NkirPmUsKF0wXcCk1RzJU3F998QkYCb+kLXCYtedCe7G7wKkssEPt8+HYbnKPWQZwkPVgkKov/zyr843ZX1qj/kXyIBicREvBtI7IkWZpxKfapf8XsTHQMRFoBrzi9w6/85tJaz8BZGfpA1I=',
  'Conceptos': [{'Cantidad': Decimal('1'),
                 'ClaveProdServ': Code('10101702', 'Trucha viva'),
                 'ClaveUnidad': Code('E48', 'Unidad de servicio'),
                 'Descripcion': 'SOME MES DE ABRIL DEL 2023',
                 'Importe': Decimal('31913.07'),
                 'Impuestos': {'Traslados': {'002|Tasa|0.160000': {'Base': Decimal('31913.07'),
                                                                   'Importe': Decimal('5106.09'),
                                                                   'Impuesto': Code('002', 'IVA'),
                                                                   'TasaOCuota': Decimal('0.160000'),
                                                                   'TipoFactor': Code('Tasa', None)}}},
                 'ObjetoImp': Code('02', 'Sí objeto de impuesto'),
                 'ValorUnitario': Decimal('31913.07')}],
  'Emisor': {'Nombre': 'CACERES XAVIER',
             'RegimenFiscal': Code('612', 'Personas Físicas con Actividades Empresariales y Profesionales'),
             'Rfc': 'CACX7605101P8'},
  'Exportacion': Code('01', 'No aplica'),
  'Fecha': datetime.datetime(2022, 1, 1, 0, 0),
  'Folio': '1002',
  'FormaPago': Code('99', 'Por definir'),
  'Impuestos': {'TotalImpuestosTrasladados': Decimal('5106.09'),
                'Traslados': {'002|Tasa|0.160000': {'Base': Decimal('31913.07'),
                                                    'Importe': Decimal('5106.09'),
                                                    'Impuesto': Code('002', 'IVA'),
                                                    'TasaOCuota': Decimal('0.160000'),
                                                    'TipoFactor': Code('Tasa', None)}}},
  'LugarExpedicion': Code('64264', None),
  'MetodoPago': Code('PPD', 'Pago en parcialidades o diferido'),
  'Moneda': Code('MXN', 'Peso Mexicano'),
  'NoCertificado': '30001000000400002300',
  'Receptor': {'DomicilioFiscalReceptor': '64264',
               'Nombre': 'PEPE ALEJANDRO LOPEZ',
               'RegimenFiscalReceptor': Code('621', 'Incorporación Fiscal'),
               'Rfc': 'ABMG891115PD7',
               'UsoCFDI': Code('G03', 'Gastos en general')},
  'Sello': 'sPQ508mowfHUkvrh0kNqXz/OJQvkdJLbiL08WMc+iid7q9AlNEgM7Qov1tCWJVsbeV8cOCgTb4T0MvoBisfALArre9RJoHjjL3VyWib3ymiKt+GTc0JB+krvboeP5YOR9J1TrLIcfR4stEdVAsB4g6reMiyAdCLjQv+0gRXg/CEY+FhrAsX2nZYHUN7FUF8o73rxmW88KVHLP15pivg6+8gutXjg4HEsoae5/f0MdU3qDvNcrF6BdP0VFsEmpxshOc560ppINICpqJy2mqYPfeaiD5Ues6gEpSCnM3t36RC6Y2KHTCgysSgDuSPHdLUgg74OcwLhdjgkjsRHNe7q0A==',
  'Serie': 'K',
  'SubTotal': Decimal('31913.07'),
  'TipoDeComprobante': Code('I', 'Ingreso'),
  'Total': Decimal('37019.16'),
  'Version': '4.0'}]